print('  __  __          _____ _____ _____   __   _')
print(' |  \/  |   /\   / ____|_   _/ ____| |  \/  | ')
print(' | \  / |  /  \ | |  __  | || |      | \  / | ')
print(' | |\/| | / /\ \| | |_ | | || |      | |\/| |')
print(' | |  | |/ ____ \ |__| |_| || |____  | |  | | ')
print(' |_|  |_/_/    \_\_____|_____\_____| |_|  |_|')
print('')
print('')
print('')
print('Hello World, I am Magic M.  °˖✧◝(⁰▿⁰)◜✧˖°')
print("I am here to make suggestions for activities I know you'll enjoy ᕙ(‾̀◡‾́)ᕗ ")
print("So, tell me more about yourself ◝(^⌣^)◜")